# Generated by Django 2.0.4 on 2018-08-11 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 5, 55, 7, 337069, tzinfo=utc), verbose_name='date added'),
        ),
    ]
